### ISSUE TITLE
Unexpected EOF when tar -xvf

### ISSUE THREAD

**Issue by jkim971201** [jshinnerl/pekoMS_2006_book#1]
Hi.
When I use tar -xvf command (ex. tar -xvf xab), it is crushed with "unexpected EOF"  error message.
I'm worrying that the files are corrupted.
Can you check the files are valid?

Thanks.

**Comment by jshinnerl** [comment]
The files are not intended to be unpacked one by one.   I have verified that the command below works fine when applied to all the files together.  Please note that first, you have to download *all* the xa* files.

                                cat x* | tar xvf -

**Comment by jshinnerl** [comment]
If this command still does not work for you, then perhaps there is some OS-incompatibility issue with file termination characters.  I would hope that could be resolved just by opening and closing the files on your system, but i don't know. I hope someone who experienced the same problem and found a work-around will share it.

**Comment by jkim971201** [comment]
Thank you so much.
It worked for me.
I apologize for not reading the README carefully.
There are nothing wrong with your instructions.

Thanks again.
